In [11]:
import pandas as pd
df = pd.read_csv('C:/Users/BEST LAPTOP/Desktop/AI/data.csv')

df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [12]:
(df.head(5)) #Display the first 5 rows of the dataset.

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [13]:
(df.tail(5)) #Display the last 5 rows.

    Duration          Date  Pulse  Maxpulse  Calories
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [14]:
print (df.shape) #Display the last 5 rows.

(32, 5)

In [16]:
df.columns

Index(['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [18]:
df.dtypes

Duration      int64
Date         object
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [19]:
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

In [20]:
max_pulse = df['Pulse'].max()
print(f"Maximum Pulse value: {max_pulse}")

Maximum Pulse value: 130

In [21]:
# Find minimum value in Duration column
min_duration = df['Duration'].min()
print(f"Minimum Duration value: {min_duration}")

Minimum Duration value: 30

In [22]:
# Find average Calories
avg_calories = df['Calories'].mean()
print(f"Average Calories burned: {avg_calories:.2f}")

Average Calories burned: 304.68

In [6]:
import pandas as pd
df = pd.read_csv('C:/Users/BEST LAPTOP/Desktop/AI/data.csv')
df['Date'] = pd.to_datetime(df['Date'], format='mixed')
(df.to_string())

'    Duration       Date  Pulse  Maxpulse  Calories\n0         60 2020-12-01    110       130     409.1\n1         60 2020-12-02    117       145     479.0\n2         60 2020-12-03    103       135     340.0\n3         45 2020-12-04    109       175     282.4\n4         45 2020-12-05    117       148     406.0\n5         60 2020-12-06    102       127     300.0\n6         60 2020-12-07    110       136     374.0\n7        450 2020-12-08    104       134     253.3\n8         30 2020-12-09    109       133     195.1\n9         60 2020-12-10     98       124     269.0\n10        60 2020-12-11    103       147     329.3\n11        60 2020-12-12    100       120     250.7\n12        60 2020-12-12    100       120     250.7\n13        60 2020-12-13    106       128     345.3\n14        60 2020-12-14    104       132     379.3\n15        60 2020-12-15     98       123     275.0\n16        60 2020-12-16     98       120     215.2\n17        60 2020-12-17    100       120     300.0\n18        45 2020-12-18     90       112       NaN\n19        60 2020-12-19    103       123     323.0\n20        45 2020-12-20     97       125     243.0\n21        60 2020-12-21    108       131     364.2\n22        45        NaT    100       119     282.0\n23        60 2020-12-23    130       101     300.0\n24        45 2020-12-24    105       132     246.0\n25        60 2020-12-25    102       126     334.5\n26        60 2020-12-26    100       120     250.0\n27        60 2020-12-27     92       118     241.0\n28        60 2020-12-28    103       132       NaN\n29        60 2020-12-29    100       132     280.0\n30        60 2020-12-30    102       129     380.3\n31        60 2020-12-31     92       115     243.0'

In [7]:
import pandas as pd
df = pd.read_csv('C:/Users/BEST LAPTOP/Desktop/AI/data.csv')
df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

In [9]:

df['Calories'] = df['Calories'].fillna(df['Calories'].mean())
print(df["Date"])

0     '2020/12/01'
1     '2020/12/02'
2     '2020/12/03'
3     '2020/12/04'
4     '2020/12/05'
5     '2020/12/06'
6     '2020/12/07'
7     '2020/12/08'
8     '2020/12/09'
9     '2020/12/10'
10    '2020/12/11'
11    '2020/12/12'
12    '2020/12/12'
13    '2020/12/13'
14    '2020/12/14'
15    '2020/12/15'
16    '2020/12/16'
17    '2020/12/17'
18    '2020/12/18'
19    '2020/12/19'
20    '2020/12/20'
21    '2020/12/21'
22             NaN
23    '2020/12/23'
24    '2020/12/24'
25    '2020/12/25'
26        20201226
27    '2020/12/27'
28    '2020/12/28'
29    '2020/12/29'
30    '2020/12/30'
31    '2020/12/31'
Name: Date, dtype: object

In [10]:
print(df["Calories"].fillna(df["Calories"].mean()))

0     409.10
1     479.00
2     340.00
3     282.40
4     406.00
5     300.00
6     374.00
7     253.30
8     195.10
9     269.00
10    329.30
11    250.70
12    250.70
13    345.30
14    379.30
15    275.00
16    215.20
17    300.00
18    304.68
19    323.00
20    243.00
21    364.20
22    282.00
23    300.00
24    246.00
25    334.50
26    250.00
27    241.00
28    304.68
29    280.00
30    380.30
31    243.00
Name: Calories, dtype: float64

In [11]:
print(df[df.duplicated()])

    Duration          Date  Pulse  Maxpulse  Calories
12        60  '2020/12/12'    100       120     250.7

In [12]:
print(df.drop_duplicates())

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130    409.10
1         60  '2020/12/02'    117       145    479.00
2         60  '2020/12/03'    103       135    340.00
3         45  '2020/12/04'    109       175    282.40
4         45  '2020/12/05'    117       148    406.00
5         60  '2020/12/06'    102       127    300.00
6         60  '2020/12/07'    110       136    374.00
7        450  '2020/12/08'    104       134    253.30
8         30  '2020/12/09'    109       133    195.10
9         60  '2020/12/10'     98       124    269.00
10        60  '2020/12/11'    103       147    329.30
11        60  '2020/12/12'    100       120    250.70
13        60  '2020/12/13'    106       128    345.30
14        60  '2020/12/14'    104       132    379.30
15        60  '2020/12/15'     98       123    275.00
16        60  '2020/12/16'     98       120    215.20
17        60  '2020/12/17'    100       120    300.00
18        45  '2020/12/18'     90       112    304.68
19        60  '2020/12/19'    103       123    323.00
20        45  '2020/12/20'     97       125    243.00
21        60  '2020/12/21'    108       131    364.20
22        45           NaN    100       119    282.00
23        60  '2020/12/23'    130       101    300.00
24        45  '2020/12/24'    105       132    246.00
25        60  '2020/12/25'    102       126    334.50
26        60      20201226    100       120    250.00
27        60  '2020/12/27'     92       118    241.00
28        60  '2020/12/28'    103       132    304.68
29        60  '2020/12/29'    100       132    280.00
30        60  '2020/12/30'    102       129    380.30
31        60  '2020/12/31'     92       115    243.00

In [13]:
print(df[df["Duration"] > 120])

   Duration          Date  Pulse  Maxpulse  Calories
7       450  '2020/12/08'    104       134     253.3

In [14]:
df.loc[df["Duration"] > 120, "Duration"] = 45
print(df)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130    409.10
1         60  '2020/12/02'    117       145    479.00
2         60  '2020/12/03'    103       135    340.00
3         45  '2020/12/04'    109       175    282.40
4         45  '2020/12/05'    117       148    406.00
5         60  '2020/12/06'    102       127    300.00
6         60  '2020/12/07'    110       136    374.00
7         45  '2020/12/08'    104       134    253.30
8         30  '2020/12/09'    109       133    195.10
9         60  '2020/12/10'     98       124    269.00
10        60  '2020/12/11'    103       147    329.30
11        60  '2020/12/12'    100       120    250.70
12        60  '2020/12/12'    100       120    250.70
13        60  '2020/12/13'    106       128    345.30
14        60  '2020/12/14'    104       132    379.30
15        60  '2020/12/15'     98       123    275.00
16        60  '2020/12/16'     98       120    215.20
17        60  '2020/12/17'    100       120    300.00
18        45  '2020/12/18'     90       112    304.68
19        60  '2020/12/19'    103       123    323.00
20        45  '2020/12/20'     97       125    243.00
21        60  '2020/12/21'    108       131    364.20
22        45           NaN    100       119    282.00
23        60  '2020/12/23'    130       101    300.00
24        45  '2020/12/24'    105       132    246.00
25        60  '2020/12/25'    102       126    334.50
26        60      20201226    100       120    250.00
27        60  '2020/12/27'     92       118    241.00
28        60  '2020/12/28'    103       132    304.68
29        60  '2020/12/29'    100       132    280.00
30        60  '2020/12/30'    102       129    380.30
31        60  '2020/12/31'     92       115    243.00

In [15]:
print(df.dropna(subset=["Date"]))

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130    409.10
1         60  '2020/12/02'    117       145    479.00
2         60  '2020/12/03'    103       135    340.00
3         45  '2020/12/04'    109       175    282.40
4         45  '2020/12/05'    117       148    406.00
5         60  '2020/12/06'    102       127    300.00
6         60  '2020/12/07'    110       136    374.00
7         45  '2020/12/08'    104       134    253.30
8         30  '2020/12/09'    109       133    195.10
9         60  '2020/12/10'     98       124    269.00
10        60  '2020/12/11'    103       147    329.30
11        60  '2020/12/12'    100       120    250.70
12        60  '2020/12/12'    100       120    250.70
13        60  '2020/12/13'    106       128    345.30
14        60  '2020/12/14'    104       132    379.30
15        60  '2020/12/15'     98       123    275.00
16        60  '2020/12/16'     98       120    215.20
17        60  '2020/12/17'    100       120    300.00
18        45  '2020/12/18'     90       112    304.68
19        60  '2020/12/19'    103       123    323.00
20        45  '2020/12/20'     97       125    243.00
21        60  '2020/12/21'    108       131    364.20
23        60  '2020/12/23'    130       101    300.00
24        45  '2020/12/24'    105       132    246.00
25        60  '2020/12/25'    102       126    334.50
26        60      20201226    100       120    250.00
27        60  '2020/12/27'     92       118    241.00
28        60  '2020/12/28'    103       132    304.68
29        60  '2020/12/29'    100       132    280.00
30        60  '2020/12/30'    102       129    380.30
31        60  '2020/12/31'     92       115    243.00

In [16]:
print(df[df["Duration"] > 60])

Empty DataFrame
Columns: [Duration, Date, Pulse, Maxpulse, Calories]
Index: []

In [17]:
print(df[df["Duration"] > 60])

Empty DataFrame
Columns: [Duration, Date, Pulse, Maxpulse, Calories]
Index: []

In [18]:
print(df[df["Calories"] > 350])

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
4         45  '2020/12/05'    117       148     406.0
6         60  '2020/12/07'    110       136     374.0
14        60  '2020/12/14'    104       132     379.3
21        60  '2020/12/21'    108       131     364.2
30        60  '2020/12/30'    102       129     380.3

In [19]:
print(df[(df["Pulse"] >= 100) & (df["Pulse"] <= 110)])

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130    409.10
2         60  '2020/12/03'    103       135    340.00
3         45  '2020/12/04'    109       175    282.40
5         60  '2020/12/06'    102       127    300.00
6         60  '2020/12/07'    110       136    374.00
7         45  '2020/12/08'    104       134    253.30
8         30  '2020/12/09'    109       133    195.10
10        60  '2020/12/11'    103       147    329.30
11        60  '2020/12/12'    100       120    250.70
12        60  '2020/12/12'    100       120    250.70
13        60  '2020/12/13'    106       128    345.30
14        60  '2020/12/14'    104       132    379.30
17        60  '2020/12/17'    100       120    300.00
19        60  '2020/12/19'    103       123    323.00
21        60  '2020/12/21'    108       131    364.20
22        45           NaN    100       119    282.00
24        45  '2020/12/24'    105       132    246.00
25        60  '2020/12/25'    102       126    334.50
26        60      20201226    100       120    250.00
28        60  '2020/12/28'    103       132    304.68
29        60  '2020/12/29'    100       132    280.00
30        60  '2020/12/30'    102       129    380.30

In [20]:
print(df[["Duration", "Calories"]])

    Duration  Calories
0         60    409.10
1         60    479.00
2         60    340.00
3         45    282.40
4         45    406.00
5         60    300.00
6         60    374.00
7         45    253.30
8         30    195.10
9         60    269.00
10        60    329.30
11        60    250.70
12        60    250.70
13        60    345.30
14        60    379.30
15        60    275.00
16        60    215.20
17        60    300.00
18        45    304.68
19        60    323.00
20        45    243.00
21        60    364.20
22        45    282.00
23        60    300.00
24        45    246.00
25        60    334.50
26        60    250.00
27        60    241.00
28        60    304.68
29        60    280.00
30        60    380.30
31        60    243.00

In [21]:
average_pulse = df["Pulse"].mean()
print("average_pulse:", average_pulse)

average_pulse: 103.5

In [22]:
day_max_calories = df.loc[df["Calories"].idxmax(), "Date"]
print("day_max_calories:", day_max_calories)

day_max_calories: '2020/12/02'

In [23]:
# Assuming your Date column looks like 20201226
df['Date'] = pd.to_datetime(df['Date'], format='mixed')

# Now calculate total Calories burned in December
total_cal_december = df[df['Date'].dt.month == 12]['Calories'].sum()
print("Total Calories burned in December:", total_cal_december)

Total Calories burned in December: 9467.76

In [24]:
average_duration_workout = df["Duration"].mean()
print("average_duration_workout:", average_duration_workout)

average_duration_workout: 55.78125

In [25]:
max_maxpulse = df["Pulse"].max()
print("max_maxpulse:", max_maxpulse)

max_maxpulse: 130

In [26]:
sorted_by_calories = df.sort_values(by='Calories', ascending=False)
print("Dataset sorted by Calories burned (descending):", sorted_by_calories)

Dataset sorted by Calories burned (descending):     Duration       Date  Pulse  Maxpulse  Calories
1         60 2020-12-02    117       145    479.00
0         60 2020-12-01    110       130    409.10
4         45 2020-12-05    117       148    406.00
30        60 2020-12-30    102       129    380.30
14        60 2020-12-14    104       132    379.30
6         60 2020-12-07    110       136    374.00
21        60 2020-12-21    108       131    364.20
13        60 2020-12-13    106       128    345.30
2         60 2020-12-03    103       135    340.00
25        60 2020-12-25    102       126    334.50
10        60 2020-12-11    103       147    329.30
19        60 2020-12-19    103       123    323.00
28        60 2020-12-28    103       132    304.68
18        45 2020-12-18     90       112    304.68
5         60 2020-12-06    102       127    300.00
23        60 2020-12-23    130       101    300.00
17        60 2020-12-17    100       120    300.00
3         45 2020-12-04    109       175    282.40
22        45        NaT    100       119    282.00
29        60 2020-12-29    100       132    280.00
15        60 2020-12-15     98       123    275.00
9         60 2020-12-10     98       124    269.00
7         45 2020-12-08    104       134    253.30
11        60 2020-12-12    100       120    250.70
12        60 2020-12-12    100       120    250.70
26        60 2020-12-26    100       120    250.00
24        45 2020-12-24    105       132    246.00
31        60 2020-12-31     92       115    243.00
20        45 2020-12-20     97       125    243.00
27        60 2020-12-27     92       118    241.00
16        60 2020-12-16     98       120    215.20
8         30 2020-12-09    109       133    195.10

In [27]:
sorted_by_pulse = df.sort_values(by='Pulse', ascending=True)
print("Dataset sorted by Pulse (ascending):", sorted_by_pulse)

Dataset sorted by Pulse (ascending):     Duration       Date  Pulse  Maxpulse  Calories
18        45 2020-12-18     90       112    304.68
27        60 2020-12-27     92       118    241.00
31        60 2020-12-31     92       115    243.00
20        45 2020-12-20     97       125    243.00
15        60 2020-12-15     98       123    275.00
9         60 2020-12-10     98       124    269.00
16        60 2020-12-16     98       120    215.20
11        60 2020-12-12    100       120    250.70
17        60 2020-12-17    100       120    300.00
22        45        NaT    100       119    282.00
29        60 2020-12-29    100       132    280.00
12        60 2020-12-12    100       120    250.70
26        60 2020-12-26    100       120    250.00
5         60 2020-12-06    102       127    300.00
30        60 2020-12-30    102       129    380.30
25        60 2020-12-25    102       126    334.50
28        60 2020-12-28    103       132    304.68
10        60 2020-12-11    103       147    329.30
2         60 2020-12-03    103       135    340.00
19        60 2020-12-19    103       123    323.00
7         45 2020-12-08    104       134    253.30
14        60 2020-12-14    104       132    379.30
24        45 2020-12-24    105       132    246.00
13        60 2020-12-13    106       128    345.30
21        60 2020-12-21    108       131    364.20
3         45 2020-12-04    109       175    282.40
8         30 2020-12-09    109       133    195.10
0         60 2020-12-01    110       130    409.10
6         60 2020-12-07    110       136    374.00
4         45 2020-12-05    117       148    406.00
1         60 2020-12-02    117       145    479.00
23        60 2020-12-23    130       101    300.00

In [28]:
average_pulse_by_duration = df.groupby('Duration')['Pulse'].mean().reset_index()
print("\nAverage Pulse by Duration:", average_pulse_by_duration)

Average Pulse by Duration:    Duration       Pulse
0        30  109.000000
1        45  103.142857
2        60  103.375000

In [29]:
avg_pulse_by_duration = df.groupby('Duration')['Pulse'].mean().reset_index()
print("\nAverage Pulse by Duration:")
print(avg_pulse_by_duration)

Average Pulse by Duration:
   Duration       Pulse
0        30  109.000000
1        45  103.142857
2        60  103.375000

In [30]:

top_5_calories = df.nlargest(5, 'Calories')
print("\nTop 5 records with highest Calories burned:")
print(top_5_calories)

Top 5 records with highest Calories burned:
    Duration       Date  Pulse  Maxpulse  Calories
1         60 2020-12-02    117       145     479.0
0         60 2020-12-01    110       130     409.1
4         45 2020-12-05    117       148     406.0
30        60 2020-12-30    102       129     380.3
14        60 2020-12-14    104       132     379.3

In [31]:
sorted_by_calories = df.sort_values(by='Calories', ascending=True)
print("\nDataset sorted by Calories burned (ascending):")
print(sorted_by_calories)

Dataset sorted by Calories burned (ascending):
    Duration       Date  Pulse  Maxpulse  Calories
8         30 2020-12-09    109       133    195.10
16        60 2020-12-16     98       120    215.20
27        60 2020-12-27     92       118    241.00
31        60 2020-12-31     92       115    243.00
20        45 2020-12-20     97       125    243.00
24        45 2020-12-24    105       132    246.00
26        60 2020-12-26    100       120    250.00
11        60 2020-12-12    100       120    250.70
12        60 2020-12-12    100       120    250.70
7         45 2020-12-08    104       134    253.30
9         60 2020-12-10     98       124    269.00
15        60 2020-12-15     98       123    275.00
29        60 2020-12-29    100       132    280.00
22        45        NaT    100       119    282.00
3         45 2020-12-04    109       175    282.40
5         60 2020-12-06    102       127    300.00
17        60 2020-12-17    100       120    300.00
23        60 2020-12-23    130       101    300.00
18        45 2020-12-18     90       112    304.68
28        60 2020-12-28    103       132    304.68
19        60 2020-12-19    103       123    323.00
10        60 2020-12-11    103       147    329.30
25        60 2020-12-25    102       126    334.50
2         60 2020-12-03    103       135    340.00
13        60 2020-12-13    106       128    345.30
21        60 2020-12-21    108       131    364.20
6         60 2020-12-07    110       136    374.00
14        60 2020-12-14    104       132    379.30
30        60 2020-12-30    102       129    380.30
4         45 2020-12-05    117       148    406.00
0         60 2020-12-01    110       130    409.10
1         60 2020-12-02    117       145    479.00

In [32]:
sorted_by_pulse = df.sort_values(by='Pulse', ascending=False)
print("\nDataset sorted by Pulse (descending):")
print(sorted_by_pulse)

Dataset sorted by Pulse (descending):
    Duration       Date  Pulse  Maxpulse  Calories
23        60 2020-12-23    130       101    300.00
1         60 2020-12-02    117       145    479.00
4         45 2020-12-05    117       148    406.00
6         60 2020-12-07    110       136    374.00
0         60 2020-12-01    110       130    409.10
3         45 2020-12-04    109       175    282.40
8         30 2020-12-09    109       133    195.10
21        60 2020-12-21    108       131    364.20
13        60 2020-12-13    106       128    345.30
24        45 2020-12-24    105       132    246.00
14        60 2020-12-14    104       132    379.30
7         45 2020-12-08    104       134    253.30
19        60 2020-12-19    103       123    323.00
2         60 2020-12-03    103       135    340.00
10        60 2020-12-11    103       147    329.30
28        60 2020-12-28    103       132    304.68
5         60 2020-12-06    102       127    300.00
30        60 2020-12-30    102       129    380.30
25        60 2020-12-25    102       126    334.50
12        60 2020-12-12    100       120    250.70
29        60 2020-12-29    100       132    280.00
26        60 2020-12-26    100       120    250.00
11        60 2020-12-12    100       120    250.70
17        60 2020-12-17    100       120    300.00
22        45        NaT    100       119    282.00
9         60 2020-12-10     98       124    269.00
15        60 2020-12-15     98       123    275.00
16        60 2020-12-16     98       120    215.20
20        45 2020-12-20     97       125    243.00
27        60 2020-12-27     92       118    241.00
31        60 2020-12-31     92       115    243.00
18        45 2020-12-18     90       112    304.68

In [33]:
top_5_calories = df.nlargest(5, 'Calories')
print("\nTop 5 records with highest Calories burned:")
print(top_5_calories)

Top 5 records with highest Calories burned:
    Duration       Date  Pulse  Maxpulse  Calories
1         60 2020-12-02    117       145     479.0
0         60 2020-12-01    110       130     409.1
4         45 2020-12-05    117       148     406.0
30        60 2020-12-30    102       129     380.3
14        60 2020-12-14    104       132     379.3

In [34]:
top_5_long_workouts = df.nlargest(5, 'Duration')
print("\nTop 5 records with longest Duration:")
print(top_5_long_workouts)

Top 5 records with longest Duration:
   Duration       Date  Pulse  Maxpulse  Calories
0        60 2020-12-01    110       130     409.1
1        60 2020-12-02    117       145     479.0
2        60 2020-12-03    103       135     340.0
5        60 2020-12-06    102       127     300.0
6        60 2020-12-07    110       136     374.0

In [35]:
df["Calories_ranking"] = df["Calories"].rank(ascending=False)
print(df["Calories_ranking"])

0      2.0
1      1.0
2      9.0
3     18.0
4      3.0
5     16.0
6      6.0
7     23.0
8     32.0
9     22.0
10    11.0
11    24.5
12    24.5
13     8.0
14     5.0
15    21.0
16    31.0
17    16.0
18    13.5
19    12.0
20    28.5
21     7.0
22    19.0
23    16.0
24    27.0
25    10.0
26    26.0
27    30.0
28    13.5
29    20.0
30     4.0
31    28.5
Name: Calories_ranking, dtype: float64

In [36]:
average_pulse = df["Pulse"].mean()
print("average_pulse:", average_pulse)

average_pulse: 103.5

In [37]:

average_duration = df["Duration"].mean()
print("average_duration:", average_duration)

average_duration: 55.78125

In [38]:
max_calories = df["Calories"].max()
print("max_calories:", max_calories)

max_calories: 479.0

In [39]:
min_pulse = df["Pulse"].min()
print("min_pulse:", min_pulse)

min_pulse: 90

In [40]:
total_calories_burned = df["Calories"].sum()
print("total_calories_burned:", total_calories_burned)

total_calories_burned: 9749.759999999998

In [41]:
count_duration_60 = df[df["Duration"] > 60]
print("Number of workouts with Duration greater than 60 minutes:", count_duration_60)

Number of workouts with Duration greater than 60 minutes: Empty DataFrame
Columns: [Duration, Date, Pulse, Maxpulse, Calories, Calories_ranking]
Index: []

In [42]:
avg_calories = df.groupby("Duration")["Calories"].mean()
print(avg_calories)

Duration
30    195.100000
45    288.197143
60    314.053333
Name: Calories, dtype: float64

In [44]:

avg_pulse = df.groupby('Duration')['Pulse'].mean()
print(avg_pulse)

Duration
30    109.000000
45    103.142857
60    103.375000
Name: Pulse, dtype: float64

In [45]:
max_pulse = df.groupby('Duration')['Pulse'].max()
print(max_pulse)

Duration
30    109
45    117
60    130
Name: Pulse, dtype: int64